require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, min_ios_version_supported
prepare_react_native_project!

workspace 'CryptoTokensApp.xcworkspace'
project 'CryptoTokensApp.xcodeproj'

target 'CryptoTokensApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'CryptoTokensAppTests' do
    inherit! :complete
  end
end

post_install do |installer|
  react_native_post_install(
    installer,
    "#{Pod::Config.instance.installation_root}/../node_modules/react-native",
    :mac_catalyst_enabled => false
  )
end
