require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

rn_path = "../node_modules/react-native"

target 'CryptoTokensApp' do
  config = use_native_modules!

  use_react_native!(
    :path => rn_path,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'CryptoTokensAppTests' do
    inherit! :complete
  end
end

post_install do |installer|
  react_native_post_install(
    installer,
    rn_path,
    :mac_catalyst_enabled => false
  )
end
